language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "dfalessi-github"
    token:
      secure: "0e4d807e6861de66bb1f20adc9cd2981db0ed562" 
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      