language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "dfalessi-github"
    token:
      secure: "1084d9189250f1ba84be43f312613ba6e658918b" 
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
